### ISSUE TITLE
Reload is not triggered when watching multiple volume dirs

### ISSUE THREAD

**Issue by dannyk81** [jimmidyson/configmap-reload#6] opened 2017-06-14 16:59 UTC
I'm setting configmap-reload in the same Pod as Prometheus to monitor two directories :

```
      - name: configmap-reload
        image: docker.tuenti.io/monitoring/configmap-reload:v0.1
        args:
          - --volume-dir=/etc/prometheus/config
          - --volume-dir=/etc/prometheus/rules
          - --webhook-url=http://localhost:9090/-/reload
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/config
          readOnly: true
        - name: rules-volume
          mountPath: /etc/prometheus/rules
          readOnly: true
```

Changing the config files in any of these volume dirs doesn't trigger a reload, if I keep just one of them - it works.

Am I missing something? any ideas?

Thanks!

**Comment by dannyk81** [comment] 2017-06-14 19:19
Correction, changes in the 2nd volume (`rules-volume`) are detected and reload happens, but any changes I push to `config-volume` are ignored.

I'm using `kubectl edit cm` command to edit the configmaps.

**Comment by wjkohnen** [comment] 2018-01-04 05:41
Works for me. I just did a manual test on local filesystem w/o kubernetes. 

ConfigMap volumes [use an atomic writer](https://github.com/kubernetes/kubernetes/blob/6d98cdbbfb055757a9846dee97dafd4177d9a222/pkg/volume/configmap/configmap.go#L232). You could familarize yourself with the mechanic [how atomic writes are implemented](https://github.com/kubernetes/kubernetes/blob/6d98cdbbfb055757a9846dee97dafd4177d9a222/pkg/volume/util/atomic_writer.go#L122). In the end you should check if the actual change you do in your ConfigMap results in the [rename of the `..data`-symlink (step 9)](https://github.com/kubernetes/kubernetes/blob/6d98cdbbfb055757a9846dee97dafd4177d9a222/pkg/volume/util/atomic_writer.go#L192). 

Note that a changed ConfigMap in the API to take visible effect in the ConfigMap volume is _very_ asynchronous, as in: can take several minutes.

**Comment by dannyk81** [comment] 2018-01-05 17:23
Thanks for the reply! I do realize that the proces is async and I waited quite a bit.

I will try again, perhaps I missed something, will also monitor the `..data` symlink as suggested.

**Comment by andjelx** [comment] 2018-01-16 15:03
Seems like we have same issue. Works perfectly on one volume monitored, but not on two.
@dannyk81 Did you get it working ?

**Comment by dannyk81** [comment] 2018-01-16 15:52
@andjelx nope :( it's still failing for me... as you said, works just fine with one volume monitored.

When there are two volumes, only the changes in the *second* volume are detected, but nothing happens when I update the first volume.

**Comment by andjelx** [comment] 2018-01-16 16:27
Seems I’ve found the root of issue. U (and me) are using old docker image (with old go programm) and seems this was fixed in latest docker  version, going to check it tomorrow.

**Comment by wjkohnen** [comment] 2018-01-17 10:05
Well, in hindsight I think it was a mistake to make `--volume-dir` usable multiples time instead of using it once but list directories comma separated. Apologies.

**Comment by dannyk81** [comment] 2018-01-17 13:06
@andjelx I was using latest release (v0.1), which one are you planning to try, `latest`?

@wjkohnen but regardless of how the flag works, it should still be supported?

Perhaps v0.1 doesn't include your PR and we should have used `latest` tag?

**Comment by wjkohnen** [comment] 2018-01-17 17:20
As of now you should use the `latest` docker tag or build your own image.

Technically you can use the `--volume-dir` flag multiple time in both versions `v0.1` and the current `latest`. In `v0.1` the last value overwrites all other values (thus watching only the second of two directories); in `latest` (with my PR) all values are appended to a list of directories which all are watched. 

@jimmidyson and I apparently didn't think of the fact that having the flag more than once in the old version would not yield an error, but silently drop parameters. This is not a bug, but a feature of the flag package in order to implement default values in scripted invocations of a Go program. This is an unfortunate lesson on how (not) to maintain fail-safe CLI compatibility.

**Comment by dannyk81** [comment] 2018-01-17 17:31
@wjkohnen understood! thanks for the detailed explanation 👍 

Would be awesome if a new (v0.2 or something) can be published with all these fixes, for now I'll just update to use `latest` tag.

@jimmidyson please 🙏

**Comment by jimmidyson** [comment] 2018-01-24 10:55
Done! v0.2.0 should be available on Docker Hub soon after https://circleci.com/gh/jimmidyson/configmap-reload/14 completes.

Thanks again to @wjkohnen for your explanation and help.

**Closed** 2018-01-24 11:40 UTC
